version: 2
updates:
  # Keep maven dependencies up-to-date
  - package-ecosystem: maven
    # Look for `pom.xml`  in the `root` directory
    directory: "/"
    # Check the maven registry for updates every day (weekdays)
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "master"    
    # Raise all maven pull requests with custom labels
    labels:
      - "maven dependencies"
    commit-message:
      prefix: requirements
    reviewers:
      - "hilpitome"
      - "ekigamba"
